// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQY_Sp61gWtcOxqVRBfePYZE_AfnL8Qvs',
    appId: '1:494422079092:web:df7f367c21ac5b725cc321',
    messagingSenderId: '494422079092',
    projectId: 'trackexp-d1b6f',
    authDomain: 'trackexp-d1b6f.firebaseapp.com',
    storageBucket: 'trackexp-d1b6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhE2pxo3pu_3F6p75uHk6ogRH23m2mL3g',
    appId: '1:494422079092:android:aa3c95dcc28c1d075cc321',
    messagingSenderId: '494422079092',
    projectId: 'trackexp-d1b6f',
    storageBucket: 'trackexp-d1b6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwQFDZvc1ksp1HNTqzOWr9pNnRV_oEFQQ',
    appId: '1:494422079092:ios:b6ac1f529c8009395cc321',
    messagingSenderId: '494422079092',
    projectId: 'trackexp-d1b6f',
    storageBucket: 'trackexp-d1b6f.appspot.com',
    iosClientId: '494422079092-vm69na91k9q8iofte2hsgi9hae95et54.apps.googleusercontent.com',
    iosBundleId: 'com.example.managment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwQFDZvc1ksp1HNTqzOWr9pNnRV_oEFQQ',
    appId: '1:494422079092:ios:b6ac1f529c8009395cc321',
    messagingSenderId: '494422079092',
    projectId: 'trackexp-d1b6f',
    storageBucket: 'trackexp-d1b6f.appspot.com',
    iosClientId: '494422079092-vm69na91k9q8iofte2hsgi9hae95et54.apps.googleusercontent.com',
    iosBundleId: 'com.example.managment',
  );
}
